services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin        # This is your Access Key
      - MINIO_ROOT_PASSWORD=password123 # This is your Secret Key
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  

  clamav:
    image: clamav/clamav:latest
    ports:
    - "3310:3310"
    volumes:
      - ./clamav/clamd.conf:/etc/clamav/clamd.conf
    healthcheck:
      test: ["CMD", "clamdcheck.sh"]
      interval: 60s
      retries: 3
      start_period: 120s  