"""fix:add display prefix to Api keys table

Revision ID: 2336ec9187ba
Revises: b805d204858c
Create Date: 2026-06-26 22:48:19.503841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2336ec9187ba'
down_revision: Union[str, Sequence[str], None] = 'b805d204858c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('display_prefix', sa.String(length=255), nullable=False), schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'display_prefix', schema='dunno_what')
    # ### end Alembic commands ###
