"""add: webhook_url and webhook_secret to Developer table

Revision ID: 612ec9983530
Revises: 9d3873bc1d17
Create Date: 2026-07-10 20:17:48.279409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612ec9983530'
down_revision: Union[str, Sequence[str], None] = '9d3873bc1d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('webhook_url', sa.String(length=2048), nullable=True), schema='dunno_what')
    op.add_column('developers', sa.Column('webhook_secret', sa.String(length=255), nullable=True), schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'webhook_secret', schema='dunno_what')
    op.drop_column('developers', 'webhook_url', schema='dunno_what')
    # ### end Alembic commands ###
