"""add:Auth tables

Revision ID: 6d1bea7deb10
Revises: cee1f417cf4e
Create Date: 2026-06-25 19:14:56.861963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1bea7deb10'
down_revision: Union[str, Sequence[str], None] = 'cee1f417cf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dunno_what'
    )
    op.create_index(op.f('ix_dunno_what_developers_email'), 'developers', ['email'], unique=True, schema='dunno_what')
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('developer_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['dunno_what.developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dunno_what'
    )
    op.create_index(op.f('ix_dunno_what_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True, schema='dunno_what')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('developer_id', sa.Uuid(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['dunno_what.developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dunno_what'
    )
    op.create_index(op.f('ix_dunno_what_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True, schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dunno_what_refresh_tokens_token'), table_name='refresh_tokens', schema='dunno_what')
    op.drop_table('refresh_tokens', schema='dunno_what')
    op.drop_index(op.f('ix_dunno_what_api_keys_key_hash'), table_name='api_keys', schema='dunno_what')
    op.drop_table('api_keys', schema='dunno_what')
    op.drop_index(op.f('ix_dunno_what_developers_email'), table_name='developers', schema='dunno_what')
    op.drop_table('developers', schema='dunno_what')
    # ### end Alembic commands ###
