"""add: developer id to jobs table

Revision ID: 92a8aa2e1a97
Revises: 612ec9983530
Create Date: 2026-08-15 16:32:00.373683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a8aa2e1a97'
down_revision: Union[str, Sequence[str], None] = '612ec9983530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('developer_id', sa.Uuid(), nullable=False), schema='dunno_what')
    op.create_index(op.f('ix_dunno_what_jobs_developer_id'), 'jobs', ['developer_id'], unique=False, schema='dunno_what')
    op.create_foreign_key(None, 'jobs', 'developers', ['developer_id'], ['id'], source_schema='dunno_what', referent_schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', schema='dunno_what', type_='foreignkey')
    op.drop_index(op.f('ix_dunno_what_jobs_developer_id'), table_name='jobs', schema='dunno_what')
    op.drop_column('jobs', 'developer_id', schema='dunno_what')
    # ### end Alembic commands ###
