"""fix:add developer_id field to file_metadata

Revision ID: 9d3873bc1d17
Revises: 2336ec9187ba
Create Date: 2026-06-26 23:20:26.854607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3873bc1d17'
down_revision: Union[str, Sequence[str], None] = '2336ec9187ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('developer_id', sa.Uuid(), nullable=False), schema='dunno_what')
    op.create_index(op.f('ix_dunno_what_file_metadata_developer_id'), 'file_metadata', ['developer_id'], unique=False, schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dunno_what_file_metadata_developer_id'), table_name='file_metadata', schema='dunno_what')
    op.drop_column('file_metadata', 'developer_id', schema='dunno_what')
    # ### end Alembic commands ###
