"""remove job_type from Job table

Revision ID: a39de233849c
Revises: f41a724a56a4
Create Date: 2026-06-22 20:55:18.803434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39de233849c'
down_revision: Union[str, Sequence[str], None] = 'f41a724a56a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_type', schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False), schema='dunno_what')
    # ### end Alembic commands ###
