"""Initial tables

Revision ID: a6b87301a528
Revises: 
Create Date: 2026-06-16 02:07:42.549209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6b87301a528'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dunno_what'
    )
    op.create_index(op.f('ix_dunno_what_jobs_upload_id'), 'jobs', ['upload_id'], unique=False, schema='dunno_what')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('routing_key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['dunno_what.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dunno_what'
    )
    op.create_index(op.f('ix_dunno_what_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False, schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dunno_what_audit_logs_job_id'), table_name='audit_logs', schema='dunno_what')
    op.drop_table('audit_logs', schema='dunno_what')
    op.drop_index(op.f('ix_dunno_what_jobs_upload_id'), table_name='jobs', schema='dunno_what')
    op.drop_table('jobs', schema='dunno_what')
    # ### end Alembic commands ###
