"""remove nullability constrain from jobs table

Revision ID: cee1f417cf4e
Revises: a39de233849c
Create Date: 2026-06-22 21:02:24.132603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cee1f417cf4e'
down_revision: Union[str, Sequence[str], None] = 'a39de233849c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='dunno_what')
    # ### end Alembic commands ###
