"""fix nullable upload_id in jobs table

Revision ID: dd729cbc8351
Revises: a6b87301a528
Create Date: 2026-06-16 02:12:46.459044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd729cbc8351'
down_revision: Union[str, Sequence[str], None] = 'a6b87301a528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'upload_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'upload_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dunno_what')
    # ### end Alembic commands ###
