"""add new filemetadata table and refined job table

Revision ID: f41a724a56a4
Revises: dd729cbc8351
Create Date: 2026-06-22 19:46:04.214826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f41a724a56a4'
down_revision: Union[str, Sequence[str], None] = 'dd729cbc8351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='dunno_what')
    op.add_column('file_metadata', sa.Column('type', sa.String(length=20), nullable=False), schema='dunno_what')
    op.add_column('file_metadata', sa.Column('storage_location', sa.String(length=255), nullable=False), schema='dunno_what')
    op.add_column('file_metadata', sa.Column('bucket', sa.String(), nullable=False), schema='dunno_what')
    op.add_column('file_metadata', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='dunno_what')
    op.add_column('file_metadata', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False), schema='dunno_what')
    op.add_column('jobs', sa.Column('file_id', sa.Uuid(), nullable=False), schema='dunno_what')
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='dunno_what')
    op.alter_column('jobs', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='dunno_what')
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='dunno_what')
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='dunno_what')
    op.drop_index(op.f('ix_dunno_what_jobs_upload_id'), table_name='jobs', schema='dunno_what')
    op.create_foreign_key(None, 'jobs', 'file_metadata', ['file_id'], ['id'], source_schema='dunno_what', referent_schema='dunno_what')
    op.drop_column('jobs', 'upload_id', schema='dunno_what')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('upload_id', sa.VARCHAR(), autoincrement=False, nullable=False), schema='dunno_what')
    op.drop_constraint(None, 'jobs', schema='dunno_what', type_='foreignkey')
    op.create_index(op.f('ix_dunno_what_jobs_upload_id'), 'jobs', ['upload_id'], unique=False, schema='dunno_what')
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='dunno_what')
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='dunno_what')
    op.alter_column('jobs', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='dunno_what')
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='dunno_what')
    op.drop_column('jobs', 'file_id', schema='dunno_what')
    op.drop_column('file_metadata', 'updated_at', schema='dunno_what')
    op.drop_column('file_metadata', 'created_at', schema='dunno_what')
    op.drop_column('file_metadata', 'bucket', schema='dunno_what')
    op.drop_column('file_metadata', 'storage_location', schema='dunno_what')
    op.drop_column('file_metadata', 'type', schema='dunno_what')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='dunno_what')
    # ### end Alembic commands ###
